"""Cloze-style probes for the learn-set.

Per the 2026-05-19 decision in docs/decisions.md, probes are template-based,
NOT generated by the model under test — paraphrasing with the same model
would leak the answer through pretraining co-occurrence statistics.

Each relation has a fixed pool of question templates that omit the object.
The cloze answer is always the fact's `obj` string verbatim, so eval can
exact-match against it.

Probe templates are defined in ``facts.RelationConfig`` (the single
source for all relation metadata). This module imports the template
accessor rather than maintaining a separate dictionary.
"""

from __future__ import annotations

import random
from dataclasses import dataclass

from .facts import Fact, relation_probe_templates


@dataclass(frozen=True)
class Probe:
    probe_id: str
    fact_id: str
    prompt: str
    flagged: bool  # mirrors fact.flagged for eval-time bucketing


def build_probes(
    facts: list[Fact], paraphrases_per_fact: int, seed: int
) -> list[Probe]:
    """Build deterministic probes for every fact.

    Sampling is *without replacement* within a fact when possible — if
    paraphrases_per_fact exceeds available templates for a relation, we
    cycle (with replacement) deterministically.
    """
    rng = random.Random(seed)
    probes: list[Probe] = []
    for fact in facts:
        templates = relation_probe_templates(fact.relation)
        if paraphrases_per_fact <= len(templates):
            chosen = rng.sample(templates, paraphrases_per_fact)
        else:
            chosen = []
            shuffled = list(templates)
            rng.shuffle(shuffled)
            while len(chosen) < paraphrases_per_fact:
                chosen.append(shuffled[len(chosen) % len(shuffled)])
        for j, tmpl in enumerate(chosen):
            probes.append(
                Probe(
                    probe_id=f"{fact.fact_id}P{j}",
                    fact_id=fact.fact_id,
                    prompt=tmpl.format(subject=fact.subject),
                    flagged=fact.flagged,
                )
            )
    return probes
